baseURL: "https://deacputri.com"
title: De's Personal Site
theme: PaperMod

minify:
    disableXML: true
    minifyOutput: true

defaultContentLanguage: en
defaultContentLanguageInSubdir: true
languages:
    en:
        languageName: English
        weight: 1
        contentDir: content/en
        languageCode: en-US
        taxonomies:
            category: categories
            tag: tags
            series: series
        params:
            languageAltTitle: English
            profileMode:
                enabled: true
                title: Dea Chintia Putri
                imageUrl: "images/dea_profile.png"
                subtitle: "Life-Long Learner | Currently a DBA | Love Playing Games"
                buttons:
                    - name: Blog
                      url: posts
                    - name: Project
                      url: projects
        menu:
            main:
                - name: Archive
                  url: archives
                  weight: 5
                - name: Search
                  url: search/
                  weight: 10
                - name: Tags
                  url: tags/
                  weight: 10
                - name: Project
                  url: projects/
                  weight: 1

    id:
        languageName: Indonesia
        weight: 2
        contentDir: content/id
        languageCode: id-ID
        taxonomies:
            category: categories
            tag: tags
            series: series
        params:
            languageAltTitle: Indonesia
            profileMode:
                enabled: true
                title: Dea Chintia Putri
                imageUrl: "images/dea_profile.png"
                subtitle: "Life-Long Learner | Seorang DBA | Senang Bermain Games"
                buttons:
                    - name: Blog
                      url: posts
                    - name: Proyek
                      url: projects
        menu:
            main:
                - name: Arsip
                  url: archives
                  weight: 5
                - name: Cari
                  url: search
                  weight: 10
                - name: Tags
                  url: tags
                  weight: 10
                - name: Proyek
                  url: projects
                  weight: 1

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "Personal website of Dea C. Putri"
    author: Dea C. Putri
    # author: ["Me", "You"] # multiple authors

    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: true
    ShowToc: true
    # comments: true

    socialIcons:
        - name: Linkedin
          url: "https://www.linkedin.com/in/deachintiaputri"
        - name: Email
          url: "mailto:dea.chintiaputri@gmail.com"
        - name: Rss
          url: "index.xml"

    label:
        text: "De's Personal Site"
        icon: "images/logo.svg"

    # analytics:
    #     google:
    #         SiteVerificationTag: "XYZabc"

    assets:
        disableHLJS: true
    #     favicon: "<link / abs url>"
    #     favicon16x16: "<link / abs url>"
    #     favicon32x32: "<link / abs url>"
    #     apple_touch_icon: "<link / abs url>"
    #     safari_pinned_tab: "<link / abs url>"

    # cover:
    #     hidden: true # hide everywhere but not in structured data
    #     hiddenInList: true # hide on list pages and home
    #     hiddenInSingle: true # hide on single page

    # fuseOpts:
    #     isCaseSensitive: false
    #     shouldSort: true
    #     location: 0
    #     distance: 1000
    #     threshold: 0.4
    #     minMatchCharLength: 0
    #     limit: 10 # refer: https://www.fusejs.io/api/methods.html#search
    #     keys: ["title", "permalink", "summary", "content"]

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        noClasses: false
        # anchorLineNos: true
        codeFences: true
        guessSyntax: true
        lineNos: true
        # style: abap

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true